title: Inside Block
description: "Dicas e tutoriais sobre internet, tecnologia, SEO, desenvolvimento web, otimização, monetização, blogs, redes sociais e muito mais!"
logo: /assets/logo/ib.png
author: Inside Block
web_designer: 'Ediano Silva Santos'

url: https://www.insideblock.com
baseurl: ""
paginate_path: "/page/:num/"
permalink: /posts/:title.html

markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate','jekyll-sitemap','jekyll-feed']
paginate: 10

compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

files_to_cache:
 - ''

pages_to_cache:
  - '/offline/index.html'

include: ['_redirects', '_headers']

google_analytics: "UA-81236717-1"
